### ISSUE TITLE
Unambiguos error message

### ISSUE THREAD

**Issue by backstube** [bjc/prosody#11]
Hi,
I'd just like to drop a suggestion here. While troubleshooting s2s connections, I get log messages like this one:
<code>incoming s2s stream example.com->jabber.example.net closed: Your server's certificate is invalid, expired, or not trusted by jabber.example.net</code>

For folks new to this matter or not administering this stuff regularly this might be confusing. Is it invalid? Or, if valid, not trusted on other grounds? Please provide a bit more specific messages.

**Comment by bjc** [comment]
Please bring this up with the official development team. This is just a git mirror of their project.
