### ISSUE TITLE
[ macOS 10.12 Sierra] brew cli install warning

### ISSUE THREAD

**Issue by dphov** [bjc/prosody#12]
`brew tap prosody/prosody`

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/prosody/homebrew-prosody/prosody.rb:9:in `<class:Prosody>'
Please report this to the prosody/prosody tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/prosody/homebrew-prosody/prosody.rb:9:in `<class:Prosody>'
Please report this to the prosody/prosody tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/prosody/homebrew-prosody/prosody.rb:9:in `<class:Prosody>'
Please report this to the prosody/prosody tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/prosody/homebrew-prosody/prosody.rb:26:in `block in <class:Prosody>'
Please report this to the prosody/prosody tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/prosody/homebrew-prosody/prosody.rb:26:in `block in <class:Prosody>'
Please report this to the prosody/prosody tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/prosody/homebrew-prosody/prosody.rb:26:in `block in <class:Prosody>'
Please report this to the prosody/prosody tap!

Tapped 1 formula (29 files, 27.2K)

`brew install prosody`
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/prosody/homebrew-prosody/prosody.rb:9:in `<class:Prosody>'
Please report this to the prosody/prosody tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/prosody/homebrew-prosody/prosody.rb:9:in `<class:Prosody>'
Please report this to the prosody/prosody tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/prosody/homebrew-prosody/prosody.rb:9:in `<class:Prosody>'
Please report this to the prosody/prosody tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/prosody/homebrew-prosody/prosody.rb:26:in `block in <class:Prosody>'
Please report this to the prosody/prosody tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/prosody/homebrew-prosody/prosody.rb:26:in `block in <class:Prosody>'
Please report this to the prosody/prosody tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/prosody/homebrew-prosody/prosody.rb:26:in `block in <class:Prosody>'
Please report this to the prosody/prosody tap!

==> Installing prosody from prosody/prosody
==> Installing dependencies for prosody/prosody/prosody: lua51, expat, libidn
==> Installing prosody/prosody/prosody dependency: lua51
==> Downloading https://homebrew.bintray.com/bottles/lua51-5.1.5_4.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring lua51-5.1.5_4.sierra.bottle.tar.gz
==> Caveats
Please be aware due to the way Luarocks is designed any binaries installed
via Luarocks-5.2 AND 5.1 will overwrite each other in /usr/local/bin.

This is, for now, unavoidable. If this is troublesome for you, you can build
rocks with the `--tree=` command to a special, non-conflicting location and
then add that to your `$PATH`.
==> Summary
🍺  /usr/local/Cellar/lua51/5.1.5_4: 135 files, 694.2K
==> Installing prosody/prosody/prosody dependency: expat
==> Downloading https://homebrew.bintray.com/bottles/expat-2.2.0.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring expat-2.2.0.sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X includes Expat 1.5.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/expat/lib
    CPPFLAGS: -I/usr/local/opt/expat/include
    PKG_CONFIG_PATH: /usr/local/opt/expat/lib/pkgconfig

==> Summary
🍺  /usr/local/Cellar/expat/2.2.0: 13 files, 381.1K
==> Installing prosody/prosody/prosody dependency: libidn
==> Downloading https://homebrew.bintray.com/bottles/libidn-1.33.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libidn-1.33.sierra.bottle.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/libidn
==> Summary
🍺  /usr/local/Cellar/libidn/1.33: 71 files, 1.3M
==> Installing prosody/prosody/prosody
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/prosody/homebrew-prosody/prosody.rb:9:in `<class:Prosody>'
Please report this to the prosody/prosody tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/prosody/homebrew-prosody/prosody.rb:9:in `<class:Prosody>'
Please report this to the prosody/prosody tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/prosody/homebrew-prosody/prosody.rb:9:in `<class:Prosody>'
Please report this to the prosody/prosody tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/prosody/homebrew-prosody/prosody.rb:26:in `block in <class:Prosody>'
Please report this to the prosody/prosody tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/prosody/homebrew-prosody/prosody.rb:26:in `block in <class:Prosody>'
Please report this to the prosody/prosody tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/prosody/homebrew-prosody/prosody.rb:26:in `block in <class:Prosody>'
Please report this to the prosody/prosody tap!

==> Downloading https://prosody.im/tmp/0.9.7/prosody-0.9.7.tar.gz
######################################################################## 100.0%
Warning: Calling Pathname#sha1 is deprecated!
Use Pathname#sha256 instead.
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:320:in `verify_checksum'

==> ./configure --prefix=/usr/local/Cellar/prosody/0.9.7 --sysconfdir=/usr/local/etc/prosody --datadir=/usr/local/var/lib/prosody --with-lua=/usr/local/opt/lua51 --with-lua-include=
==> make
==> make install
==> make install
==> Downloading http://luarocks.org/releases/luarocks-2.2.0.tar.gz
==> Downloading from http://keplerproject.github.io/luarocks/releases/luarocks-2.2.0.tar.gz
######################################################################## 100.0%
Warning: Calling Pathname#sha1 is deprecated!
Use Pathname#sha256 instead.
/usr/local/Homebrew/Library/Taps/prosody/homebrew-prosody/prosody.rb:68:in `install'
Please report this to the prosody/prosody tap!

==> ./configure --prefix=/usr/local/Cellar/prosody/0.9.7/libexec --rocks-tree=/usr/local/Cellar/prosody/0.9.7/libexec --sysconfdir=/usr/local/Cellar/prosody/0.9.7/libexec/etc/luaroc
==> make build
==> make install
==> /usr/local/Cellar/prosody/0.9.7/bin/prosody-luarocks install luasocket
==> /usr/local/Cellar/prosody/0.9.7/bin/prosody-luarocks install luasec
==> /usr/local/Cellar/prosody/0.9.7/bin/prosody-luarocks install luafilesystem
==> /usr/local/Cellar/prosody/0.9.7/bin/prosody-luarocks install luaexpat EXPAT_DIR=/usr/local/opt/expat
==> Caveats
TODO: proper docs
Rocks install to: /usr/local/Cellar/prosody/0.9.7/libexec/lib/luarocks/rocks

You may need to run `prosody-luarocks install` inside the Homebrew build
environment for rocks to successfully build. To do this, first run `brew sh`.
==> Summary
🍺  /usr/local/Cellar/prosody/0.9.7: 394 files, 2.9M, built in 52 seconds

`brew -v`
Homebrew 1.0.6
Homebrew/homebrew-core (git revision 5b51; last commit 2016-10-06)

**Comment by bjc** [comment]
This is not the official Prosody repository, it is simply a git mirror of their Mercurial repo. Please report all issues to the official site at http://prosody.im
