### ISSUE TITLE
Unable to send file when "http_upload" is enabled in Prosody server configuration

### ISSUE THREAD

**Issue by Myhappyapps** [bjc/prosody#15]
I express my sincere thanks for providing great project Prosody. I am using Conversations as client. I enabled "http_upload" in Prosody server so that i am getting attachment icon in conference chat and XEP-0363 is available in Server Info also.

My issue is if i enabled "http_upload" in Prosody server then I am unable to send files even in single contact as well as in Conference chat. But if i disable "http_upload" , i am able to send files in single contacts.

Please help. Thanking you.

**Comment by bjc** [comment]
Clone of Prosody's Mercurial Repository, please do not file PRs or bug reports here, but go to the official website instead. http://prosody.im
