### ISSUE TITLE
Error: Should be able to do TLS but no context available

### ISSUE THREAD

**Issue by socialloser1** [bjc/prosody#18]
OS : archlinux
client can not sign in , no matter how I change the config file, here is server log:

May 16 06:07:01 alarm prosody[1496]: c2s27c314b0: Client connected
May 16 06:07:01 alarm prosody[1496]: c2s27c314b0: Client sent opening <stream:stream> to server.xmpp
May 16 06:07:01 alarm prosody[1496]: c2s27c314b0: Sent reply <stream:stream> to client
May 16 06:07:01 alarm prosody[1496]: c2s27c314b0: Not offering authentication on insecure connection
May 16 06:07:01 alarm prosody[1496]: c2s27c314b0: Should be able to do TLS but no context available
May 16 06:07:01 alarm prosody[1496]: socket: server.lua: client 192.168.1.196:55223 read error: close

**Comment by bjc** [comment]
Clone of Prosody's Mercurial Repository, please do not file PRs or bug reports here, but go to the official website instead. http://prosody.im
