### ISSUE TITLE
Please move to prosody/prosody and give rights to official devs

### ISSUE THREAD

**Issue by Neustradamus** [bjc/prosody#20]
Can you move to https://github.com/prosody/prosody for have official code?
https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

**Comment by bjc** [comment]
I'd be happy to transfer it to them, but AFAIK, they're not interested (or, at least, they haven't inquired).

**Comment by Neustradamus** [comment]
@bjc Ok :/ but it is possible to update it?

**Comment by mwild1** [comment]
I can confirm that we (Prosody team) have no desire to manage a mirror on Github.

It's an open-source project, and anybody is entitled to put a copy of the code wherever they want. Our only concern would be people sending PRs/issue reports and not understanding that the repository is not official and not monitored by the Prosody team.

**Comment by bjc** [comment]
@Neustradamus Should be being updated now. A change from python to python2 had left it un-updated.
