### ISSUE TITLE
the debian init script use constant user name which causes permission issue.

### ISSUE THREAD

**Issue by wxwok** [bjc/prosody#22]
In the ubuntu source code version 0.9.12, the debian/prosody.init, the default USER name is "prosody". I need to run the service under my user name, so I changed the var USER. Then the service restart failed, it reports the /var/run/prosody/prosody.pid can't be changed, it doesn't have permission to change it. In the prosody.init, the start_prosody():
start_prosody () {
        mkdir -p `dirname $PIDFILE`
        chown prosody:adm `dirname $PIDFILE`
        if start-stop-daemon --start --quiet --pidfile "$PIDFILE" \
                --chuid "$USER" --oknodo --user "$USER" --name lua5.1 \
                $(start_opts) --startas "$DAEMON";
        then
                return 0
        else
                return 1
        fi
}

the chown command should use the $USER variable.
The debian directory is not included in this github. So I don't know where to submit issue.

**Comment by bjc** [comment]
Please submit this to the official repository at prosody.im. This is merely a github clone.
