### ISSUE TITLE
throttle.lua floor

### ISSUE THREAD

**Issue by Hypher** [bjc/prosody#6]
At https://github.com/bjc/prosody/blob/master/util/throttle.lua#L15 the floor is problematic.
Assume you have a rate of 1, if you call :update() more than one per second (through :poll for instance), your balance will never raise!
I didn't find any problems letting balance being a float. So removing the floor fixes the problem I mentioned.
(I use throttle for anti-flood purposes)

**Comment by Zash** [comment]
This is not an official bug tracker for Prosody. Please don't file issues here.

**Comment by bjc** [comment]
What Kim said.

**Comment by Zash** [comment]
See https://prosody.im/bugs/ for how to report bugs against Prosody.
