### ISSUE TITLE
Non-anonynous rooms in MUC

### ISSUE THREAD

**Issue by Dafvid** [bjc/prosody#7]
Hi
Is there a setting somewhere to make rooms "non-anonymous"? I need the actual JID to be sent with the message and not the username as a resource.

see also:
http://xmpp.org/extensions/xep-0045.html#enter-nonanon

**Comment by bjc** [comment]
I only maintain the github mirror of prosody. Please ask the prosody developers directly.

**Comment by Dafvid** [comment]
Oops sorry.
