### ISSUE TITLE
Replace Speeqe by Candy

### ISSUE THREAD

**Issue by GreenLunar** [bjc/prosody#8]
`(join via <a class="component" href="xmpp:gajim@conference.gajim.org?join">client</a> / <a class="component" href="http://speeqe.com/room/gajim@conference.gajim.org/">speeqe</a>)`

Unlike Candy, Speeqe does not offer its interface in different languages.  I suggest to use Candy instead.

Public instances of Candy https://github.com/candy-chat/candy/wiki/Candy-Instances

**Comment by GreenLunar** [comment]
> Note: I do not know of a public instance of Candy.

https://github.com/candy-chat/candy/wiki/Candy-Instances

**Comment by bjc** [comment]
This is not the official Prosody repository -- which is hosted at http://prosody.im/  -- this is just a git clone of it. Issues should be brought up at the official site.

**Comment by GreenLunar** [comment]
Done.

Reference: https://prosody.im/issues/issue/573
