### ISSUE TITLE
Empty "var" attribute in "feature" element during service discovery

### ISSUE THREAD

**Issue by grigoryfedorov** [bjc/prosody#9]
Here is the discussion redsolution/xabber-android#528

```
<iq id="X5cF8-15" type="result" to="michal@przybys.eu/phone2" from="przybys.eu">
   <query xmlns="http://jabber.org/protocol/disco#info">
      <identity type="pep" name="Prosody" category="pubsub" />
      <identity type="im" name="Prosody" category="server" />
      <feature var="http://jabber.org/protocol/pubsub#publish" />
      <feature var="urn:xmpp:archive:auto" />
      <feature var="urn:xmpp:archive:manage" />
      <feature var="urn:xmpp:archive:pref" />
      <feature xmlns="urn:xmpp:archive">
         <optional>
            <default />
         </optional>
      </feature>
   </query>
</iq>
```

The problem is that last "feature" element does not contain "var" attribute. 
> Each <feature/> element MUST possess a 'var' attribute whose value is a protocol namespace or other feature offered by the entity.

http://xmpp.org/extensions/xep-0030.html

Is it a bug or am I wrong?

**Comment by bjc** [comment]
First thing: this is not the official Prosody repository, just a git clone of the official Mercurial one hosted at http://prosody.im/ -- All issues should be brought up there.

However, the MAM <feature/> is clearly wrong. The "xmlns" attribute should be "var" instead, and there's no capacity for the <optional/> element it contains. <feature/> contains no sub-structure. For details you can look at XEP-0030 § 11.1
